server:
  port: 8400

spring:
  cloud:
    discovery:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  queue:
    name: image-processor
