services:
  message-broker:
    build:
      context: .
      dockerfile: rabbit/Dockerfile
    container_name: local-rabbit-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wierd_arts

  db:
    image: postgres:15.2-alpine
    container_name: local-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wierd_arts
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wierd_arts

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yd@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - '5050:80'
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - wierd_arts

  gateway:
    container_name: gateway
    build:
      context: ../../gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - wierd_arts

  service-registry:
    container_name: service-registry
    build:
      context: ../../service-registry
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - wierd_arts

  gallery-service:
    container_name: gallery-service
    build:
      context: ../../gallery-service
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    networks:
      - wierd_arts
    depends_on:
      - db

  image-service:
    container_name: image-service
    build:
      context: ../../image-service
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    networks:
      - wierd_arts
    depends_on:
      - message-broker

  image-processing-service:
    container_name: image-processing-service
    build:
      context: ../../image-processing-service
      dockerfile: Dockerfile
    ports:
      - 8400:8400
    networks:
      - wierd_arts
    depends_on:
      - message-broker

volumes:
  pgdata:
  pgadmindata:

networks:
  wierd_arts: