stages:
  - pre-build
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" ||
        ($CI_PIPELINE_SOURCE == 'merge_request_event' &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"))

include:
  - local: '/.gitlab/build.yml'