variables:
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
  TF_ROOT: deployments/aws/terraform/wierd_arts

stages:
  - pre-build
  - build
  - test
  - post-build
  - deploy
  - destroy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" ||
        ($CI_PIPELINE_SOURCE == 'merge_request_event' &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"))

include:
  - local: '/.gitlab/build.yml'
  - local: '/.gitlab/deploy.yml'
  - local: '/.gitlab/destroy.yml'
