services:
  gallery-service:
    container_name: gallery-service
    build:
      context: ./gallery-service
      dockerfile: Dockerfile
    image: yd/gallery-service:latest
    ports:
      - "8100:8100"
    networks:
      - spring-cloud-network
  image-service:
    container_name: image-service
    build:
      context: ./image-service
      dockerfile: Dockerfile
    image: yd/image-service:latest
    ports:
      - "8200:8200"
    networks:
      - spring-cloud-network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  spring-cloud-network:
    driver: bridge