services:
  gallery-service:
    container_name: gallery-service
    build:
      context: ./gallery-service
      dockerfile: Dockerfile
    image: gallery-service:latest
    ports:
      - "8100:8100"
    networks:
      - spring-cloud-network
  image-service:
    container_name: image-service
    build:
      context: ./image-service
      dockerfile: Dockerfile
    image: image-service:latest
    ports:
      - "8200:8200"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge