server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/dev_yashodha_space
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
        - id: gallery-service
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery/**