server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/image/**
        - id: gallery-service
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery/**