.maven-build:
  extends:
    - .run-maven-goal
  stage: build
  variables:
    MVN_GOALS: 'package'

build-gallery-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: gallery-service

.run-maven-goal:
  image: maven:latest
  stage: build
    - chmod +x ./scripts/maven_exec.sh
    - bash scripts/maven_exec.sh $SERVICE_NAME $MVN_GOALS
