build-gallery-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: gallery-service

build-image-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: image-service

build-image-processing-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: image-processing-service

preparing-docker-images:
  image: docker:dind
  stage: post-build
  script:
    - sh .gitlab/scripts/docker.sh $SERVICE_NAME

.maven-build:
  extends:
    - .run-maven-goal
  variables:
    MVN_GOALS: 'package'

.run-maven-goal:
  image: maven:latest
  stage: build
  script:
    - bash .gitlab/scripts/maven.sh $SERVICE_NAME $MVN_GOALS
    - mkdir -p artifacts/$SERVICE_NAME
    - cp $SERVICE_NAME/target/*.jar artifacts/$SERVICE_NAME/
  artifacts:
    when: on_success
    expire_in: 10 min
    paths:
      - artifacts/