build-gallery-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: gallery-service

.maven-build:
  extends:
    - .run-maven-goal
  variables:
    MVN_GOALS: 'package'

.run-maven-goal:
  image: maven:latest
  stage: build
  script:
    - pwd
    - bash .gitlab/scripts/maven_exec.sh $SERVICE_NAME $MVN_GOALS
