build-gallery-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: gallery-service

build-image-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: image-service

build-image-processing-service:
  extends: .maven-build
  variables:
    SERVICE_NAME: image-processing-service

.maven-build:
  extends:
    - .run-maven-goal
  variables:
    MVN_GOALS: 'package'

.run-maven-goal:
  image: maven:latest
  stage: build
  script:
    - bash .gitlab/scripts/maven.sh $SERVICE_NAME $MVN_GOALS
    - mkdir -p artifacts
    - cp $SERVICE_NAME/target/*.jar artifacts/
    - docker build -t ${SERVICE_NAME}:latest -t 008744601422.dkr.ecr.ap-south-1.amazonaws.com/${SERVICE_NAME}:latest -f Dockerfile artifacts/
  artifacts:
    when: on_success
    expire_in: 1 hrs
    paths:
      - artifacts/