server:
  port: 8400

spring:
  cloud:
    discovery:
      enabled: true
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

app:
  queue:
    name: image-processor

eureka:
  client:
    enabled: ${ENABLE_EUREKA:false}