kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galleryRoleBinding
  namespace: wierd-arts
subjects:
  - kind: ServiceAccount
    name: gallery-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: galleryRole
  apiGroup: ""