apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: wierd-arts
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Never
          image: k8/gateway:latest
          env:
            - name: ENABLE_EUREKA
              value: 'false'
            - name: OAUTH_ISSUER_URI
              value: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_VtTCFeOSo

